Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/LeadingCommentSpace:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never